### ISSUE TITLE
DIFFERENT SOLUTION FROM DIFFERENT PRODUCTS

### ISSUE THREAD

**Issue by Giorgio-Del-Ciondolo** [PrideLab/PRIDE-PPPAR#23]
Hello to everyone :)
I launched the same daily RINEX file with the same Options but with different products (GUI version).
One solution was obtained with the default products, the other solution instead with products downloaded from the AIUB (Astronomical Institute of the University of Bern) library. 

The default products have the following names:

COD0R03FIN_20060110000_01D_01D_ERP
IGS2R03FIN_20060110000_01D_01D_OSB
IGS2R03FIN_20060110000_01D_05M_ORB
IGS2R03FIN_20060110000_01D_30S_ATT
IGS2R03FIN_20060110000_01D_30S_CLK

The Bern products have the following names:

COD0R03FIN_20060110000_01D_01D_ERP
COD0R03FIN_20060110000_01D_01D_OSB
COD0R03FIN_20060110000_01D_05M_ORB
COD0R03FIN_20060110000_01D_15M_ATT
COD0R03FIN_20060110000_01D_05S_CLK

Of course I obtained different solution but the differences were quite significant, as shown below.

![differences_myproducts_default_K](https://github.com/PrideLab/PRIDE-PPPAR/assets/169454989/054374c8-e54e-4e06-8c28-2ab712bfebba)

I used Matlab to compute that differences ( default products solution minus Bern products solution ). Differences in height are expressed in meters, the Time in Second Of Day.
I report some significant data:

mean of Height differences:                                            0.0060 m
mean of Height absolute differences:                             0.0100 m
maximum Height difference:                                           0.0870 m
minimum Height difference:                                          -0.0840 m

Do You know why that solutions are so different? Could be because the default products are not produced in block, but come from different data center?

Thank You so much in advance for every kind of answer.

**Comment by PrideLab** [comment]
Are you computing 1-Hz data? What station are you computing? You may send us your data at pride@whu.edu.cn

**Comment by PrideLab** [comment]
IGS2 denotes those combined products which should have higher robustness than AC-specific products such as those from CODE. Such a large difference normally means that AC products have some problems. We computed one station on this day using IGS2 and COD as well. The results showed that they indeed had significant differences.

![5325aecdfd7d6d8d58e69299ac3af078](https://github.com/PrideLab/PRIDE-PPPAR/assets/48112921/5b56c074-5688-49f6-be32-211e1cb5600a)
![99d661eef7b54f88d6f31b85fd0dc522](https://github.com/PrideLab/PRIDE-PPPAR/assets/48112921/304db26a-84f9-4a02-aa06-5a42450765d0)

**Comment by Giorgio-Del-Ciondolo** [comment]
Thank You so much for Your time!
