### ISSUE TITLE
Does the tide models covers the entire earth?

### ISSUE THREAD

**Issue by Giorgio-Del-Ciondolo** [PrideLab/PRIDE-PPPAR#25]
Hello to everyone ! :)
I am processing a dataset of RINEX file collected in Antarctica with a GUI version.
During a test we observe that the solution of a RINEX file processed including all tides (SOLID/OCEAN/POLE) and the solution of the same RINEX file processed without the Ocean Load Tide have the same Height. 
The differcences in NORTH and EAST local coordinates between the two solutions are in the order of 0.5 - 1.5 mm.
How is it possible ?

I have attached a RINEX of that dataset.
[dry10150.06o.txt](https://github.com/user-attachments/files/16286091/dry10150.06o.txt)

Thank You so much in advance for every kind of answer.

**Comment by PrideLab** [comment]
It's because you have no oceanloading coefficients for this site. You can find in the header of your pos or kin file to see that the "OCEAN" keyword is missing. We are releasing a new version that could produce oceanloading corrections based on an internal model rather than a external source.

**Comment by PrideLab** [comment]
Now the latest version has the capability of calculating ocean loading corrections itself.

**Comment by Giorgio-Del-Ciondolo** [comment]
Thank You for Your support !
