### ISSUE TITLE
Minor Typo in GUI Version — ZTD Plotting

### ISSUE THREAD

**Issue by Waley04** [PrideLab/PRIDE-PPPAR#9]
Dear Developers,

I suspect that **ZDD** in the Y-axis for the upper panel of the **ZTD plot** is a typo. I think it is **ZHD**. Please, refer to the following plot:

![ztd_2023100_abpo](https://github.com/PrideLab/PRIDE-PPPAR/assets/101952777/bf23a6db-eba1-4697-9683-805db2f42a1c)

Note: I observed this in the latest commit. 

Thanks with regards,

Waley.

**Comment by PrideLab** [comment]
Thank you for your report.

This may be a misunderstanding. The acronym “ZDD” stands for “Zenith Dry Delay” and is used as an alternative name for “ZHD” or “Zenith Hydrostatic Delay.” According to [C. Rocken (2001)](https://journals.ametsoc.org/view/journals/atot/18/7/1520-0426_2001_018_1205_imotd_2_0_co_2.xml?tab_body=pdf), and etc., these two terms are basically the same.

**Comment by Waley04** [comment]
@PrideLab,
 
Thank you for providing clarification on the acronyms. I already know about this relationship, however,  I was under the impression that ZHD is the commonly used acronym.

I apologize for any inconvenience caused.

Otherwise, I have taken note of this information with kind regards.

Waley.
